### ISSUE TITLE
shader code mismatch with Micro-Mesh_Rasterization.pdf

### ISSUE THREAD

**Issue by ychding11** [nvpro-samples/vk_displacement_micromaps#2]
In pdf Micro-Mesh_Rasterization.pdf
![image](https://github.com/nvpro-samples/vk_displacement_micromaps/assets/982386/36ebc4fa-21e7-4d92-9fe2-32768322ac11)

In code: vk_displacement_micromaps\micromesh_binpack.glsl
MicroDecoderConfig MicroBinPack_subgroupUnpack(uint wgroupID)
`  // compare against offsets using warp
  uint  offsetM    = uint(MICROBINPACK_IN.pack_info[laneID]) & MICRO_BIN_PACK_OFFSET_MASK;
  uvec4 vote       = subgroupBallot(wgroupID >= offsetM);
  uint inID        = subgroupBallotFindMSB(vote);
  uint partID      = wgroupID - subgroupShuffle(offsetM, inID);
`
uint inID        = subgroupBallotFindMSB(vote);  this shall pick id==3 not 1??

**Comment by pixeljetstream** [comment]
it's true that the implementation doesn't match the description in the slides here. Meaning we broadcast the last winner for the condition, and then do a few more lookups and corrections to get the start index into output data and the relative index. However it would still work if implemented like in the slides.

edit: as shown later, the comparison offsetM is not same as in slides, so inID does return 1, rather than 3.

**Comment by ychding11** [comment]
```
    // within bin, compute new offset based on how many meshlets already were 
    // done for this bin (partID many), and then the local packID we are
    inID             = min( packStart + (partID * packSize) + packID, SUBGROUP_SIZE-1);
```
    
    
![image](https://github.com/nvpro-samples/vk_displacement_micromaps/assets/982386/bf438d87-faba-4e01-964c-57240ebf8cf1)
packStart == 3
partID  == 0
packID == {0,1,2,3}

I feel it will read wrong data?

**Comment by pixeljetstream** [comment]
hm, I think you are correct, I wonder why it's working / why I had removed the code in the comment. Maybe I found that packing happens to work out.

`uint packStart = inID; // (pack >> MICRO_BIN_PACK_START_SHIFT) & MICRO_BIN_PACK_START_MASK;`

originally the packStart value was stored in the pack configuration. I looked into the development history of the internal repository but unfortunately I didn't leave a commit message explaining this change.

**Comment by pixeljetstream** [comment]
actually no, all is good.

If we look at the comment (line 171), the offsetM that is compared with and stored, is different to the illustration. That is why findMSB actually does return the first of the group and `inID` / `packStart` is correct. 😅 

in the illustration we stored and compared with 
0 4 4 4 5 5
result was defined as "first" where wgroupID >= array value, here 1

but offsetM that is stored and compared with in the shader is different, it's
0 4 5 5 5 6
result is here defined as "last" where wgroupID >= array value, here also 1

it's the start meshlet for the first entry of a packed group of same subdivision, but then for the other array members it's the start of the next group. That is achieved in the line 124.

sorry for the confusion, the slides are older and as the comment around `packStart = inID //..` suggests it used to be implemented differently.
